# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataTransUi.ui'
#
# Created: Fri Sep 12 10:22:13 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dataTransWidget(object):
    def setupUi(self, dataTransWidget):
        dataTransWidget.setObjectName(_fromUtf8("dataTransWidget"))
        dataTransWidget.resize(675, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/airplane.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dataTransWidget.setWindowIcon(icon)
        self.verticalLayout_5 = QtGui.QVBoxLayout(dataTransWidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_5 = QtGui.QLabel(dataTransWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_11 = QtGui.QLabel(dataTransWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_17.addWidget(self.label_11)
        self.cbBalanceSty = QtGui.QComboBox(dataTransWidget)
        self.cbBalanceSty.setMinimumSize(QtCore.QSize(150, 0))
        self.cbBalanceSty.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cbBalanceSty.setStatusTip(_fromUtf8(""))
        self.cbBalanceSty.setObjectName(_fromUtf8("cbBalanceSty"))
        self.horizontalLayout_17.addWidget(self.cbBalanceSty)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.pbtnBalanceParamsSetting = QtGui.QPushButton(dataTransWidget)
        self.pbtnBalanceParamsSetting.setObjectName(_fromUtf8("pbtnBalanceParamsSetting"))
        self.horizontalLayout_17.addWidget(self.pbtnBalanceParamsSetting)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.groupBox = QtGui.QGroupBox(dataTransWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtModelArea = QtGui.QLineEdit(self.groupBox)
        self.txtModelArea.setAutoFillBackground(False)
        self.txtModelArea.setObjectName(_fromUtf8("txtModelArea"))
        self.gridLayout.addWidget(self.txtModelArea, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.txtDeltaY = QtGui.QLineEdit(self.groupBox)
        self.txtDeltaY.setObjectName(_fromUtf8("txtDeltaY"))
        self.gridLayout.addWidget(self.txtDeltaY, 2, 4, 1, 1)
        self.txtDeltaX = QtGui.QLineEdit(self.groupBox)
        self.txtDeltaX.setObjectName(_fromUtf8("txtDeltaX"))
        self.gridLayout.addWidget(self.txtDeltaX, 1, 4, 1, 1)
        self.txtDeltaZ = QtGui.QLineEdit(self.groupBox)
        self.txtDeltaZ.setObjectName(_fromUtf8("txtDeltaZ"))
        self.gridLayout.addWidget(self.txtDeltaZ, 3, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.txtModelSpan = QtGui.QLineEdit(self.groupBox)
        self.txtModelSpan.setObjectName(_fromUtf8("txtModelSpan"))
        self.gridLayout.addWidget(self.txtModelSpan, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.txtWindSpeed = QtGui.QLineEdit(self.groupBox)
        self.txtWindSpeed.setObjectName(_fromUtf8("txtWindSpeed"))
        self.gridLayout.addWidget(self.txtWindSpeed, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.txtModelRefChord = QtGui.QLineEdit(self.groupBox)
        self.txtModelRefChord.setObjectName(_fromUtf8("txtModelRefChord"))
        self.gridLayout.addWidget(self.txtModelRefChord, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.txtModelRootChord = QtGui.QLineEdit(self.groupBox)
        self.txtModelRootChord.setObjectName(_fromUtf8("txtModelRootChord"))
        self.gridLayout.addWidget(self.txtModelRootChord, 2, 1, 1, 1)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 2, 5, 1)
        self.pbtnModelDataExport = QtGui.QPushButton(self.groupBox)
        self.pbtnModelDataExport.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbtnModelDataExport.setObjectName(_fromUtf8("pbtnModelDataExport"))
        self.gridLayout.addWidget(self.pbtnModelDataExport, 4, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.pbtnModelDataInput = QtGui.QPushButton(self.groupBox)
        self.pbtnModelDataInput.setObjectName(_fromUtf8("pbtnModelDataInput"))
        self.gridLayout.addWidget(self.pbtnModelDataInput, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(dataTransWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSingleFile = QtGui.QWidget()
        self.tabSingleFile.setObjectName(_fromUtf8("tabSingleFile"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabSingleFile)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabSingleFile)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 1, 1, 3)
        self.txtAeroFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtAeroFile.setObjectName(_fromUtf8("txtAeroFile"))
        self.gridLayout_2.addWidget(self.txtAeroFile, 6, 2, 1, 1)
        self.pbtnAeroFile = QtGui.QPushButton(self.groupBox_2)
        self.pbtnAeroFile.setObjectName(_fromUtf8("pbtnAeroFile"))
        self.gridLayout_2.addWidget(self.pbtnAeroFile, 6, 3, 1, 1)
        self.pbtnDynamicFile = QtGui.QPushButton(self.groupBox_2)
        self.pbtnDynamicFile.setObjectName(_fromUtf8("pbtnDynamicFile"))
        self.gridLayout_2.addWidget(self.pbtnDynamicFile, 2, 3, 1, 1)
        self.txtStaticFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtStaticFile.setObjectName(_fromUtf8("txtStaticFile"))
        self.gridLayout_2.addWidget(self.txtStaticFile, 1, 2, 1, 1)
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 7, 1, 1, 3)
        self.txtDynamicFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtDynamicFile.setObjectName(_fromUtf8("txtDynamicFile"))
        self.gridLayout_2.addWidget(self.txtDynamicFile, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 5, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 6, 1, 1, 1)
        self.pbtnStaticFile = QtGui.QPushButton(self.groupBox_2)
        self.pbtnStaticFile.setObjectName(_fromUtf8("pbtnStaticFile"))
        self.gridLayout_2.addWidget(self.pbtnStaticFile, 1, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 1, 1, 1)
        self.txtBodyFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtBodyFile.setObjectName(_fromUtf8("txtBodyFile"))
        self.gridLayout_2.addWidget(self.txtBodyFile, 5, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 3, 1, 1, 3)
        self.pbtnBodyFile = QtGui.QPushButton(self.groupBox_2)
        self.pbtnBodyFile.setObjectName(_fromUtf8("pbtnBodyFile"))
        self.gridLayout_2.addWidget(self.pbtnBodyFile, 5, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 4, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tabSingleFile, _fromUtf8(""))
        self.tabBatchFile = QtGui.QWidget()
        self.tabBatchFile.setObjectName(_fromUtf8("tabBatchFile"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.tabBatchFile)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.chbBatchStaticFile = QtGui.QCheckBox(self.tabBatchFile)
        self.chbBatchStaticFile.setObjectName(_fromUtf8("chbBatchStaticFile"))
        self.horizontalLayout_10.addWidget(self.chbBatchStaticFile)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.pbtnBatchStaticFile = QtGui.QPushButton(self.tabBatchFile)
        self.pbtnBatchStaticFile.setEnabled(False)
        self.pbtnBatchStaticFile.setObjectName(_fromUtf8("pbtnBatchStaticFile"))
        self.horizontalLayout_10.addWidget(self.pbtnBatchStaticFile)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.txtBatchStaticFile = QtGui.QLineEdit(self.tabBatchFile)
        self.txtBatchStaticFile.setEnabled(False)
        self.txtBatchStaticFile.setObjectName(_fromUtf8("txtBatchStaticFile"))
        self.verticalLayout_6.addWidget(self.txtBatchStaticFile)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_19 = QtGui.QLabel(self.tabBatchFile)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_4.addWidget(self.label_19)
        self.txtBatchDynFileReg = QtGui.QLineEdit(self.tabBatchFile)
        self.txtBatchDynFileReg.setObjectName(_fromUtf8("txtBatchDynFileReg"))
        self.verticalLayout_4.addWidget(self.txtBatchDynFileReg)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pbtnBatchAddDir = QtGui.QPushButton(self.tabBatchFile)
        self.pbtnBatchAddDir.setObjectName(_fromUtf8("pbtnBatchAddDir"))
        self.horizontalLayout_11.addWidget(self.pbtnBatchAddDir)
        self.pbtnBatchDelDir = QtGui.QPushButton(self.tabBatchFile)
        self.pbtnBatchDelDir.setObjectName(_fromUtf8("pbtnBatchDelDir"))
        self.horizontalLayout_11.addWidget(self.pbtnBatchDelDir)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.listWidgetBatchDirs = QtGui.QListWidget(self.tabBatchFile)
        self.listWidgetBatchDirs.setObjectName(_fromUtf8("listWidgetBatchDirs"))
        self.verticalLayout_6.addWidget(self.listWidgetBatchDirs)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pbtnBatchResultDir = QtGui.QPushButton(self.tabBatchFile)
        self.pbtnBatchResultDir.setObjectName(_fromUtf8("pbtnBatchResultDir"))
        self.horizontalLayout_13.addWidget(self.pbtnBatchResultDir)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.txtBatchResultDir = QtGui.QLineEdit(self.tabBatchFile)
        self.txtBatchResultDir.setObjectName(_fromUtf8("txtBatchResultDir"))
        self.verticalLayout_8.addWidget(self.txtBatchResultDir)
        self.groupBox_10 = QtGui.QGroupBox(self.tabBatchFile)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.listWidgetBatchFiles = QtGui.QListWidget(self.groupBox_10)
        self.listWidgetBatchFiles.setObjectName(_fromUtf8("listWidgetBatchFiles"))
        self.horizontalLayout_12.addWidget(self.listWidgetBatchFiles)
        self.verticalLayout_8.addWidget(self.groupBox_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tabBatchFile, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.spbFileHeaderNums = QtGui.QSpinBox(self.groupBox_3)
        self.spbFileHeaderNums.setMaximum(50)
        self.spbFileHeaderNums.setProperty("value", 1)
        self.spbFileHeaderNums.setObjectName(_fromUtf8("spbFileHeaderNums"))
        self.horizontalLayout_3.addWidget(self.spbFileHeaderNums)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spbFileFooterNums = QtGui.QSpinBox(self.groupBox_4)
        self.spbFileFooterNums.setMaximum(50)
        self.spbFileFooterNums.setProperty("value", 0)
        self.spbFileFooterNums.setObjectName(_fromUtf8("spbFileFooterNums"))
        self.horizontalLayout_5.addWidget(self.spbFileFooterNums)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.spbAngleStartCol = QtGui.QSpinBox(self.groupBox_5)
        self.spbAngleStartCol.setMaximum(50)
        self.spbAngleStartCol.setProperty("value", 1)
        self.spbAngleStartCol.setObjectName(_fromUtf8("spbAngleStartCol"))
        self.horizontalLayout_6.addWidget(self.spbAngleStartCol)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.spbAngleEndCol = QtGui.QSpinBox(self.groupBox_6)
        self.spbAngleEndCol.setMaximum(50)
        self.spbAngleEndCol.setProperty("value", 3)
        self.spbAngleEndCol.setObjectName(_fromUtf8("spbAngleEndCol"))
        self.horizontalLayout_7.addWidget(self.spbAngleEndCol)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.spbForceStartCol = QtGui.QSpinBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbForceStartCol.sizePolicy().hasHeightForWidth())
        self.spbForceStartCol.setSizePolicy(sizePolicy)
        self.spbForceStartCol.setMaximum(50)
        self.spbForceStartCol.setSingleStep(1)
        self.spbForceStartCol.setProperty("value", 4)
        self.spbForceStartCol.setObjectName(_fromUtf8("spbForceStartCol"))
        self.horizontalLayout_8.addWidget(self.spbForceStartCol)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.spbForceEndCol = QtGui.QSpinBox(self.groupBox_8)
        self.spbForceEndCol.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbForceEndCol.sizePolicy().hasHeightForWidth())
        self.spbForceEndCol.setSizePolicy(sizePolicy)
        self.spbForceEndCol.setMaximum(50)
        self.spbForceEndCol.setProperty("value", 9)
        self.spbForceEndCol.setObjectName(_fromUtf8("spbForceEndCol"))
        self.horizontalLayout_9.addWidget(self.spbForceEndCol)
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.rbAngleEuler = QtGui.QRadioButton(self.groupBox_9)
        self.rbAngleEuler.setChecked(True)
        self.rbAngleEuler.setObjectName(_fromUtf8("rbAngleEuler"))
        self.verticalLayout_7.addWidget(self.rbAngleEuler)
        self.rbAngleAero = QtGui.QRadioButton(self.groupBox_9)
        self.rbAngleAero.setEnabled(False)
        self.rbAngleAero.setObjectName(_fromUtf8("rbAngleAero"))
        self.verticalLayout_7.addWidget(self.rbAngleAero)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_18 = QtGui.QLabel(dataTransWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_14.addWidget(self.label_18)
        self.txtColumnOffset = QtGui.QLineEdit(dataTransWidget)
        self.txtColumnOffset.setObjectName(_fromUtf8("txtColumnOffset"))
        self.horizontalLayout_14.addWidget(self.txtColumnOffset)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pbtnBalanceInfo = QtGui.QPushButton(dataTransWidget)
        self.pbtnBalanceInfo.setObjectName(_fromUtf8("pbtnBalanceInfo"))
        self.horizontalLayout_4.addWidget(self.pbtnBalanceInfo)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.pbtnGenerateFile = QtGui.QPushButton(dataTransWidget)
        self.pbtnGenerateFile.setObjectName(_fromUtf8("pbtnGenerateFile"))
        self.horizontalLayout_4.addWidget(self.pbtnGenerateFile)
        self.pbtnHelp = QtGui.QPushButton(dataTransWidget)
        self.pbtnHelp.setObjectName(_fromUtf8("pbtnHelp"))
        self.horizontalLayout_4.addWidget(self.pbtnHelp)
        self.pbtnExit = QtGui.QPushButton(dataTransWidget)
        self.pbtnExit.setObjectName(_fromUtf8("pbtnExit"))
        self.horizontalLayout_4.addWidget(self.pbtnExit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_2.setBuddy(self.txtModelSpan)
        self.label.setBuddy(self.txtModelArea)
        self.label_7.setBuddy(self.txtDeltaX)
        self.label_8.setBuddy(self.txtDeltaY)
        self.label_9.setBuddy(self.txtDeltaZ)
        self.label_4.setBuddy(self.txtWindSpeed)
        self.label_3.setBuddy(self.txtModelRefChord)
        self.label_10.setBuddy(self.txtModelRootChord)
        self.label_13.setBuddy(self.txtBodyFile)
        self.label_15.setBuddy(self.txtAeroFile)
        self.label_12.setBuddy(self.txtStaticFile)
        self.label_14.setBuddy(self.txtDynamicFile)

        self.retranslateUi(dataTransWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.pbtnExit, QtCore.SIGNAL(_fromUtf8("clicked()")), dataTransWidget.close)
        QtCore.QObject.connect(self.chbBatchStaticFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbtnBatchStaticFile.setEnabled)
        QtCore.QObject.connect(self.chbBatchStaticFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtBatchStaticFile.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(dataTransWidget)

    def retranslateUi(self, dataTransWidget):
        dataTransWidget.setWindowTitle(_translate("dataTransWidget", "天平数据转换", None))
        self.label_5.setText(_translate("dataTransWidget", "实验数据转换", None))
        self.label_11.setText(_translate("dataTransWidget", "天平类型", None))
        self.cbBalanceSty.setToolTip(_translate("dataTransWidget", "选择天平类型", None))
        self.pbtnBalanceParamsSetting.setText(_translate("dataTransWidget", "天平参数设置", None))
        self.groupBox.setTitle(_translate("dataTransWidget", "模型参数", None))
        self.label_2.setText(_translate("dataTransWidget", "展长（m）", None))
        self.label.setText(_translate("dataTransWidget", "参考面积（㎡）", None))
        self.txtModelArea.setText(_translate("dataTransWidget", "0.", None))
        self.label_6.setText(_translate("dataTransWidget", "模型重心距天平位置：", None))
        self.txtDeltaY.setText(_translate("dataTransWidget", "0.", None))
        self.txtDeltaX.setText(_translate("dataTransWidget", "0.", None))
        self.txtDeltaZ.setText(_translate("dataTransWidget", "0.", None))
        self.label_7.setText(_translate("dataTransWidget", "ΔX（m）", None))
        self.label_8.setText(_translate("dataTransWidget", "ΔY（m）", None))
        self.label_9.setText(_translate("dataTransWidget", "ΔZ（m）", None))
        self.txtModelSpan.setText(_translate("dataTransWidget", "0.", None))
        self.label_4.setText(_translate("dataTransWidget", "实验风速（m/s）", None))
        self.txtWindSpeed.setText(_translate("dataTransWidget", "0.", None))
        self.label_3.setText(_translate("dataTransWidget", "平均气动弦长（m）", None))
        self.txtModelRefChord.setText(_translate("dataTransWidget", "0.", None))
        self.label_10.setText(_translate("dataTransWidget", "根弦长（m）", None))
        self.txtModelRootChord.setText(_translate("dataTransWidget", "0.", None))
        self.pbtnModelDataExport.setText(_translate("dataTransWidget", "模型参数导出...", None))
        self.pbtnModelDataInput.setText(_translate("dataTransWidget", "载入模型参数", None))
        self.groupBox_2.setTitle(_translate("dataTransWidget", "数据文件", None))
        self.label_16.setText(_translate("dataTransWidget", "请选择原始数据文件目录：", None))
        self.pbtnAeroFile.setText(_translate("dataTransWidget", "...", None))
        self.pbtnDynamicFile.setText(_translate("dataTransWidget", "...", None))
        self.label_13.setText(_translate("dataTransWidget", "体轴文件", None))
        self.label_15.setText(_translate("dataTransWidget", "风轴文件", None))
        self.pbtnStaticFile.setText(_translate("dataTransWidget", "...", None))
        self.label_12.setText(_translate("dataTransWidget", "静态文件", None))
        self.label_14.setText(_translate("dataTransWidget", "动态文件", None))
        self.pbtnBodyFile.setText(_translate("dataTransWidget", "...", None))
        self.label_17.setText(_translate("dataTransWidget", "选择生成数据文件目录：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSingleFile), _translate("dataTransWidget", "单文件", None))
        self.chbBatchStaticFile.setText(_translate("dataTransWidget", "单一静态文件", None))
        self.pbtnBatchStaticFile.setText(_translate("dataTransWidget", "选择静态文件", None))
        self.label_19.setText(_translate("dataTransWidget", "动/静文件校验符(用西文分号;隔开)", None))
        self.txtBatchDynFileReg.setText(_translate("dataTransWidget", "d.txt;j.txt", None))
        self.pbtnBatchAddDir.setText(_translate("dataTransWidget", "添加目录", None))
        self.pbtnBatchDelDir.setText(_translate("dataTransWidget", "删除目录", None))
        self.pbtnBatchResultDir.setText(_translate("dataTransWidget", "生成文件存储目录", None))
        self.groupBox_10.setTitle(_translate("dataTransWidget", "待处理文件", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBatchFile), _translate("dataTransWidget", "多文件", None))
        self.groupBox_3.setTitle(_translate("dataTransWidget", "Header行数", None))
        self.groupBox_4.setTitle(_translate("dataTransWidget", "Footer行数", None))
        self.groupBox_5.setTitle(_translate("dataTransWidget", "角度起始列", None))
        self.groupBox_6.setTitle(_translate("dataTransWidget", "角度终止列", None))
        self.groupBox_7.setTitle(_translate("dataTransWidget", "力和力矩起始列", None))
        self.groupBox_8.setTitle(_translate("dataTransWidget", "力和力矩终止列", None))
        self.groupBox_9.setTitle(_translate("dataTransWidget", "角度类型", None))
        self.rbAngleEuler.setText(_translate("dataTransWidget", "欧拉角", None))
        self.rbAngleAero.setText(_translate("dataTransWidget", "气动角", None))
        self.label_18.setText(_translate("dataTransWidget", "角度偏移量", None))
        self.pbtnBalanceInfo.setText(_translate("dataTransWidget", "查看Info", None))
        self.pbtnGenerateFile.setText(_translate("dataTransWidget", "生成数据文件...", None))
        self.pbtnHelp.setText(_translate("dataTransWidget", "帮助", None))
        self.pbtnExit.setText(_translate("dataTransWidget", "退出", None))

import imgs_rc
