# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataTransUi.ui'
#
# Created: Sun Dec 28 13:38:49 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dataTransWidget(object):
    def setupUi(self, dataTransWidget):
        dataTransWidget.setObjectName(_fromUtf8("dataTransWidget"))
        dataTransWidget.resize(591, 646)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/airplane.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dataTransWidget.setWindowIcon(icon)
        self.verticalLayout_5 = QtGui.QVBoxLayout(dataTransWidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.layoutTop = QtGui.QHBoxLayout()
        self.layoutTop.setObjectName(_fromUtf8("layoutTop"))
        self.label_11 = QtGui.QLabel(dataTransWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.layoutTop.addWidget(self.label_11)
        self.cbBalanceSty = QtGui.QComboBox(dataTransWidget)
        self.cbBalanceSty.setMinimumSize(QtCore.QSize(150, 0))
        self.cbBalanceSty.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cbBalanceSty.setStatusTip(_fromUtf8(""))
        self.cbBalanceSty.setObjectName(_fromUtf8("cbBalanceSty"))
        self.cbBalanceSty.addItem(_fromUtf8(""))
        self.cbBalanceSty.addItem(_fromUtf8(""))
        self.cbBalanceSty.addItem(_fromUtf8(""))
        self.cbBalanceSty.addItem(_fromUtf8(""))
        self.cbBalanceSty.addItem(_fromUtf8(""))
        self.layoutTop.addWidget(self.cbBalanceSty)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutTop.addItem(spacerItem)
        self.pbtnBalanceParamsSetting = QtGui.QPushButton(dataTransWidget)
        self.pbtnBalanceParamsSetting.setObjectName(_fromUtf8("pbtnBalanceParamsSetting"))
        self.layoutTop.addWidget(self.pbtnBalanceParamsSetting)
        self.verticalLayout_5.addLayout(self.layoutTop)
        self.layoutMid = QtGui.QVBoxLayout()
        self.layoutMid.setObjectName(_fromUtf8("layoutMid"))
        self.groupBox = QtGui.QGroupBox(dataTransWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtDeltaY = QtGui.QLineEdit(self.groupBox)
        self.txtDeltaY.setObjectName(_fromUtf8("txtDeltaY"))
        self.gridLayout.addWidget(self.txtDeltaY, 2, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtDeltaX = QtGui.QLineEdit(self.groupBox)
        self.txtDeltaX.setObjectName(_fromUtf8("txtDeltaX"))
        self.gridLayout.addWidget(self.txtDeltaX, 1, 4, 1, 1)
        self.txtDeltaZ = QtGui.QLineEdit(self.groupBox)
        self.txtDeltaZ.setObjectName(_fromUtf8("txtDeltaZ"))
        self.gridLayout.addWidget(self.txtDeltaZ, 3, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.txtModelArea = QtGui.QLineEdit(self.groupBox)
        self.txtModelArea.setAutoFillBackground(False)
        self.txtModelArea.setObjectName(_fromUtf8("txtModelArea"))
        self.gridLayout.addWidget(self.txtModelArea, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtModelRefChord = QtGui.QLineEdit(self.groupBox)
        self.txtModelRefChord.setObjectName(_fromUtf8("txtModelRefChord"))
        self.gridLayout.addWidget(self.txtModelRefChord, 3, 1, 1, 1)
        self.txtModelSpan = QtGui.QLineEdit(self.groupBox)
        self.txtModelSpan.setObjectName(_fromUtf8("txtModelSpan"))
        self.gridLayout.addWidget(self.txtModelSpan, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 2, 5, 1)
        self.txtWindSpeed = QtGui.QLineEdit(self.groupBox)
        self.txtWindSpeed.setObjectName(_fromUtf8("txtWindSpeed"))
        self.gridLayout.addWidget(self.txtWindSpeed, 4, 1, 1, 1)
        self.pbtnModelDataExport = QtGui.QPushButton(self.groupBox)
        self.pbtnModelDataExport.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbtnModelDataExport.setObjectName(_fromUtf8("pbtnModelDataExport"))
        self.gridLayout.addWidget(self.pbtnModelDataExport, 4, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.pbtnModelDataInput = QtGui.QPushButton(self.groupBox)
        self.pbtnModelDataInput.setObjectName(_fromUtf8("pbtnModelDataInput"))
        self.gridLayout.addWidget(self.pbtnModelDataInput, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.txtModelRootChord = QtGui.QLineEdit(self.groupBox)
        self.txtModelRootChord.setObjectName(_fromUtf8("txtModelRootChord"))
        self.gridLayout.addWidget(self.txtModelRootChord, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget = QtGui.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSingleFile = QtGui.QWidget()
        self.tabSingleFile.setObjectName(_fromUtf8("tabSingleFile"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabSingleFile)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabSingleFile)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.txtStaticFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtStaticFile.setObjectName(_fromUtf8("txtStaticFile"))
        self.gridLayout_2.addWidget(self.txtStaticFile, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 5, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 6, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 1, 1, 3)
        self.txtBodyFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtBodyFile.setObjectName(_fromUtf8("txtBodyFile"))
        self.gridLayout_2.addWidget(self.txtBodyFile, 5, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 3, 1, 1, 3)
        self.pbtnBodyFile = QtGui.QPushButton(self.groupBox_2)
        self.pbtnBodyFile.setObjectName(_fromUtf8("pbtnBodyFile"))
        self.gridLayout_2.addWidget(self.pbtnBodyFile, 5, 3, 1, 1)
        self.pbtnDynamicFile = QtGui.QPushButton(self.groupBox_2)
        self.pbtnDynamicFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbtnDynamicFile.setObjectName(_fromUtf8("pbtnDynamicFile"))
        self.gridLayout_2.addWidget(self.pbtnDynamicFile, 2, 3, 1, 1)
        self.txtAeroFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtAeroFile.setObjectName(_fromUtf8("txtAeroFile"))
        self.gridLayout_2.addWidget(self.txtAeroFile, 6, 2, 1, 1)
        self.pbtnStaticFile = QtGui.QPushButton(self.groupBox_2)
        self.pbtnStaticFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbtnStaticFile.setObjectName(_fromUtf8("pbtnStaticFile"))
        self.gridLayout_2.addWidget(self.pbtnStaticFile, 1, 3, 1, 1)
        self.txtDynamicFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtDynamicFile.setObjectName(_fromUtf8("txtDynamicFile"))
        self.gridLayout_2.addWidget(self.txtDynamicFile, 2, 2, 1, 1)
        self.pbtnAeroFile = QtGui.QPushButton(self.groupBox_2)
        self.pbtnAeroFile.setObjectName(_fromUtf8("pbtnAeroFile"))
        self.gridLayout_2.addWidget(self.pbtnAeroFile, 6, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 4, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tabSingleFile, _fromUtf8(""))
        self.tabBatchFile = QtGui.QWidget()
        self.tabBatchFile.setObjectName(_fromUtf8("tabBatchFile"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.tabBatchFile)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.chbBatchStaticFile = QtGui.QCheckBox(self.tabBatchFile)
        self.chbBatchStaticFile.setObjectName(_fromUtf8("chbBatchStaticFile"))
        self.horizontalLayout_10.addWidget(self.chbBatchStaticFile)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.pbtnBatchStaticFile = QtGui.QPushButton(self.tabBatchFile)
        self.pbtnBatchStaticFile.setEnabled(False)
        self.pbtnBatchStaticFile.setObjectName(_fromUtf8("pbtnBatchStaticFile"))
        self.horizontalLayout_10.addWidget(self.pbtnBatchStaticFile)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.txtBatchStaticFile = QtGui.QLineEdit(self.tabBatchFile)
        self.txtBatchStaticFile.setEnabled(False)
        self.txtBatchStaticFile.setObjectName(_fromUtf8("txtBatchStaticFile"))
        self.verticalLayout_6.addWidget(self.txtBatchStaticFile)
        self.label_19 = QtGui.QLabel(self.tabBatchFile)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_6.addWidget(self.label_19)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_18 = QtGui.QLabel(self.tabBatchFile)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_9.addWidget(self.label_18)
        self.txtBatchStaFileReg = QtGui.QLineEdit(self.tabBatchFile)
        self.txtBatchStaFileReg.setObjectName(_fromUtf8("txtBatchStaFileReg"))
        self.horizontalLayout_9.addWidget(self.txtBatchStaFileReg)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_28 = QtGui.QLabel(self.tabBatchFile)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_16.addWidget(self.label_28)
        self.txtBatchDynFileReg = QtGui.QLineEdit(self.tabBatchFile)
        self.txtBatchDynFileReg.setObjectName(_fromUtf8("txtBatchDynFileReg"))
        self.horizontalLayout_16.addWidget(self.txtBatchDynFileReg)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pbtnBatchAddDir = QtGui.QPushButton(self.tabBatchFile)
        self.pbtnBatchAddDir.setObjectName(_fromUtf8("pbtnBatchAddDir"))
        self.horizontalLayout_11.addWidget(self.pbtnBatchAddDir)
        self.pbtnBatchDelDir = QtGui.QPushButton(self.tabBatchFile)
        self.pbtnBatchDelDir.setObjectName(_fromUtf8("pbtnBatchDelDir"))
        self.horizontalLayout_11.addWidget(self.pbtnBatchDelDir)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.listWidgetBatchDirs = QtGui.QListWidget(self.tabBatchFile)
        self.listWidgetBatchDirs.setObjectName(_fromUtf8("listWidgetBatchDirs"))
        self.verticalLayout_6.addWidget(self.listWidgetBatchDirs)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pbtnBatchResultDir = QtGui.QPushButton(self.tabBatchFile)
        self.pbtnBatchResultDir.setObjectName(_fromUtf8("pbtnBatchResultDir"))
        self.horizontalLayout_13.addWidget(self.pbtnBatchResultDir)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.txtBatchResultDir = QtGui.QLineEdit(self.tabBatchFile)
        self.txtBatchResultDir.setObjectName(_fromUtf8("txtBatchResultDir"))
        self.verticalLayout_8.addWidget(self.txtBatchResultDir)
        self.groupBox_10 = QtGui.QGroupBox(self.tabBatchFile)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.listWidgetBatchFiles = QtGui.QListWidget(self.groupBox_10)
        self.listWidgetBatchFiles.setObjectName(_fromUtf8("listWidgetBatchFiles"))
        self.horizontalLayout_12.addWidget(self.listWidgetBatchFiles)
        self.verticalLayout_8.addWidget(self.groupBox_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tabBatchFile, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.layoutMid.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_3.addWidget(self.label_24)
        self.spbFileHeaderNums = QtGui.QSpinBox(self.groupBox_3)
        self.spbFileHeaderNums.setMaximum(50)
        self.spbFileHeaderNums.setProperty("value", 1)
        self.spbFileHeaderNums.setObjectName(_fromUtf8("spbFileHeaderNums"))
        self.horizontalLayout_3.addWidget(self.spbFileHeaderNums)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_5.addWidget(self.label_25)
        self.spbFileFooterNums = QtGui.QSpinBox(self.groupBox_3)
        self.spbFileFooterNums.setMaximum(50)
        self.spbFileFooterNums.setProperty("value", 0)
        self.spbFileFooterNums.setObjectName(_fromUtf8("spbFileFooterNums"))
        self.horizontalLayout_5.addWidget(self.spbFileFooterNums)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.chbTime = QtGui.QCheckBox(self.groupBox_3)
        self.chbTime.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chbTime.setAutoFillBackground(False)
        self.chbTime.setChecked(True)
        self.chbTime.setObjectName(_fromUtf8("chbTime"))
        self.horizontalLayout_14.addWidget(self.chbTime)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_9 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rbAngleEuler = QtGui.QRadioButton(self.groupBox_9)
        self.rbAngleEuler.setChecked(True)
        self.rbAngleEuler.setObjectName(_fromUtf8("rbAngleEuler"))
        self.horizontalLayout_2.addWidget(self.rbAngleEuler)
        self.chbTheta = QtGui.QCheckBox(self.groupBox_9)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chbTheta.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chbTheta.setFont(font)
        self.chbTheta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbTheta.setAutoFillBackground(False)
        self.chbTheta.setChecked(True)
        self.chbTheta.setObjectName(_fromUtf8("chbTheta"))
        self.horizontalLayout_2.addWidget(self.chbTheta)
        self.spbThetaCol = QtGui.QSpinBox(self.groupBox_9)
        self.spbThetaCol.setSuffix(_fromUtf8(""))
        self.spbThetaCol.setPrefix(_fromUtf8(""))
        self.spbThetaCol.setMinimum(1)
        self.spbThetaCol.setMaximum(50)
        self.spbThetaCol.setProperty("value", 2)
        self.spbThetaCol.setObjectName(_fromUtf8("spbThetaCol"))
        self.horizontalLayout_2.addWidget(self.spbThetaCol)
        self.chbPsi = QtGui.QCheckBox(self.groupBox_9)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chbPsi.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chbPsi.setFont(font)
        self.chbPsi.setChecked(True)
        self.chbPsi.setObjectName(_fromUtf8("chbPsi"))
        self.horizontalLayout_2.addWidget(self.chbPsi)
        self.spbPsiCol = QtGui.QSpinBox(self.groupBox_9)
        self.spbPsiCol.setMinimum(1)
        self.spbPsiCol.setMaximum(50)
        self.spbPsiCol.setProperty("value", 3)
        self.spbPsiCol.setObjectName(_fromUtf8("spbPsiCol"))
        self.horizontalLayout_2.addWidget(self.spbPsiCol)
        self.chbPhi = QtGui.QCheckBox(self.groupBox_9)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chbPhi.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chbPhi.setFont(font)
        self.chbPhi.setChecked(True)
        self.chbPhi.setObjectName(_fromUtf8("chbPhi"))
        self.horizontalLayout_2.addWidget(self.chbPhi)
        self.spbPhiCol = QtGui.QSpinBox(self.groupBox_9)
        self.spbPhiCol.setMinimum(1)
        self.spbPhiCol.setMaximum(50)
        self.spbPhiCol.setProperty("value", 4)
        self.spbPhiCol.setObjectName(_fromUtf8("spbPhiCol"))
        self.horizontalLayout_2.addWidget(self.spbPhiCol)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.rbAngleAero = QtGui.QRadioButton(self.groupBox_9)
        self.rbAngleAero.setEnabled(True)
        self.rbAngleAero.setObjectName(_fromUtf8("rbAngleAero"))
        self.horizontalLayout_6.addWidget(self.rbAngleAero)
        self.chbAlpha = QtGui.QCheckBox(self.groupBox_9)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chbAlpha.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chbAlpha.setFont(font)
        self.chbAlpha.setChecked(False)
        self.chbAlpha.setObjectName(_fromUtf8("chbAlpha"))
        self.horizontalLayout_6.addWidget(self.chbAlpha)
        self.spbAlphaCol = QtGui.QSpinBox(self.groupBox_9)
        self.spbAlphaCol.setEnabled(False)
        self.spbAlphaCol.setMinimum(1)
        self.spbAlphaCol.setMaximum(50)
        self.spbAlphaCol.setProperty("value", 1)
        self.spbAlphaCol.setObjectName(_fromUtf8("spbAlphaCol"))
        self.horizontalLayout_6.addWidget(self.spbAlphaCol)
        self.chbBeta = QtGui.QCheckBox(self.groupBox_9)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chbBeta.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chbBeta.setFont(font)
        self.chbBeta.setChecked(False)
        self.chbBeta.setObjectName(_fromUtf8("chbBeta"))
        self.horizontalLayout_6.addWidget(self.chbBeta)
        self.spbBetaCol = QtGui.QSpinBox(self.groupBox_9)
        self.spbBetaCol.setEnabled(False)
        self.spbBetaCol.setMinimum(1)
        self.spbBetaCol.setMaximum(50)
        self.spbBetaCol.setProperty("value", 2)
        self.spbBetaCol.setObjectName(_fromUtf8("spbBetaCol"))
        self.horizontalLayout_6.addWidget(self.spbBetaCol)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.groupBox_5 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_26 = QtGui.QLabel(self.groupBox_5)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_8.addWidget(self.label_26)
        self.spbFMStartCol = QtGui.QSpinBox(self.groupBox_5)
        self.spbFMStartCol.setProperty("value", 6)
        self.spbFMStartCol.setObjectName(_fromUtf8("spbFMStartCol"))
        self.horizontalLayout_8.addWidget(self.spbFMStartCol)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_27 = QtGui.QLabel(self.groupBox_5)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_7.addWidget(self.label_27)
        self.spbFMEndCol = QtGui.QSpinBox(self.groupBox_5)
        self.spbFMEndCol.setEnabled(False)
        self.spbFMEndCol.setMaximum(50)
        self.spbFMEndCol.setProperty("value", 11)
        self.spbFMEndCol.setObjectName(_fromUtf8("spbFMEndCol"))
        self.horizontalLayout_7.addWidget(self.spbFMEndCol)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.layoutMid.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.layoutMid)
        self.layoutBottom = QtGui.QHBoxLayout()
        self.layoutBottom.setObjectName(_fromUtf8("layoutBottom"))
        self.pbtnBalanceInfo = QtGui.QPushButton(dataTransWidget)
        self.pbtnBalanceInfo.setObjectName(_fromUtf8("pbtnBalanceInfo"))
        self.layoutBottom.addWidget(self.pbtnBalanceInfo)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutBottom.addItem(spacerItem6)
        self.pbtnGenerateFile = QtGui.QPushButton(dataTransWidget)
        self.pbtnGenerateFile.setObjectName(_fromUtf8("pbtnGenerateFile"))
        self.layoutBottom.addWidget(self.pbtnGenerateFile)
        self.pbtnHelp = QtGui.QPushButton(dataTransWidget)
        self.pbtnHelp.setObjectName(_fromUtf8("pbtnHelp"))
        self.layoutBottom.addWidget(self.pbtnHelp)
        self.pbtnExit = QtGui.QPushButton(dataTransWidget)
        self.pbtnExit.setObjectName(_fromUtf8("pbtnExit"))
        self.layoutBottom.addWidget(self.pbtnExit)
        self.verticalLayout_5.addLayout(self.layoutBottom)
        self.label_2.setBuddy(self.txtModelSpan)
        self.label.setBuddy(self.txtModelArea)
        self.label_8.setBuddy(self.txtDeltaY)
        self.label_10.setBuddy(self.txtModelRootChord)
        self.label_7.setBuddy(self.txtDeltaX)
        self.label_3.setBuddy(self.txtModelRefChord)
        self.label_4.setBuddy(self.txtWindSpeed)
        self.label_9.setBuddy(self.txtDeltaZ)
        self.label_13.setBuddy(self.txtBodyFile)
        self.label_15.setBuddy(self.txtAeroFile)
        self.label_12.setBuddy(self.txtStaticFile)
        self.label_14.setBuddy(self.txtDynamicFile)
        self.label_18.setBuddy(self.txtBatchStaFileReg)
        self.label_28.setBuddy(self.txtBatchDynFileReg)
        self.label_24.setBuddy(self.spbFileHeaderNums)
        self.label_25.setBuddy(self.spbFileFooterNums)
        self.label_26.setBuddy(self.spbFMStartCol)
        self.label_27.setBuddy(self.spbFMEndCol)

        self.retranslateUi(dataTransWidget)
        self.cbBalanceSty.setCurrentIndex(-1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pbtnExit, QtCore.SIGNAL(_fromUtf8("clicked()")), dataTransWidget.close)
        QtCore.QObject.connect(self.chbTheta, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spbThetaCol.setEnabled)
        QtCore.QObject.connect(self.chbPsi, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spbPsiCol.setEnabled)
        QtCore.QObject.connect(self.chbPhi, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spbPhiCol.setEnabled)
        QtCore.QObject.connect(self.chbAlpha, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spbAlphaCol.setEnabled)
        QtCore.QObject.connect(self.chbBeta, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spbBetaCol.setEnabled)
        QtCore.QObject.connect(self.rbAngleEuler, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chbTheta.setEnabled)
        QtCore.QObject.connect(self.rbAngleEuler, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chbPsi.setEnabled)
        QtCore.QObject.connect(self.rbAngleEuler, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chbPhi.setEnabled)
        QtCore.QObject.connect(self.rbAngleAero, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chbAlpha.setEnabled)
        QtCore.QObject.connect(self.rbAngleAero, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chbBeta.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(dataTransWidget)
        dataTransWidget.setTabOrder(self.cbBalanceSty, self.pbtnBalanceParamsSetting)
        dataTransWidget.setTabOrder(self.pbtnBalanceParamsSetting, self.txtModelArea)
        dataTransWidget.setTabOrder(self.txtModelArea, self.txtModelSpan)
        dataTransWidget.setTabOrder(self.txtModelSpan, self.txtModelRootChord)
        dataTransWidget.setTabOrder(self.txtModelRootChord, self.txtModelRefChord)
        dataTransWidget.setTabOrder(self.txtModelRefChord, self.txtWindSpeed)
        dataTransWidget.setTabOrder(self.txtWindSpeed, self.txtDeltaX)
        dataTransWidget.setTabOrder(self.txtDeltaX, self.txtDeltaY)
        dataTransWidget.setTabOrder(self.txtDeltaY, self.txtDeltaZ)
        dataTransWidget.setTabOrder(self.txtDeltaZ, self.pbtnModelDataInput)
        dataTransWidget.setTabOrder(self.pbtnModelDataInput, self.pbtnModelDataExport)
        dataTransWidget.setTabOrder(self.pbtnModelDataExport, self.txtStaticFile)
        dataTransWidget.setTabOrder(self.txtStaticFile, self.pbtnStaticFile)
        dataTransWidget.setTabOrder(self.pbtnStaticFile, self.txtDynamicFile)
        dataTransWidget.setTabOrder(self.txtDynamicFile, self.pbtnDynamicFile)
        dataTransWidget.setTabOrder(self.pbtnDynamicFile, self.txtBodyFile)
        dataTransWidget.setTabOrder(self.txtBodyFile, self.pbtnBodyFile)
        dataTransWidget.setTabOrder(self.pbtnBodyFile, self.txtAeroFile)
        dataTransWidget.setTabOrder(self.txtAeroFile, self.pbtnAeroFile)
        dataTransWidget.setTabOrder(self.pbtnAeroFile, self.spbFileHeaderNums)
        dataTransWidget.setTabOrder(self.spbFileHeaderNums, self.spbFileFooterNums)
        dataTransWidget.setTabOrder(self.spbFileFooterNums, self.rbAngleEuler)
        dataTransWidget.setTabOrder(self.rbAngleEuler, self.spbThetaCol)
        dataTransWidget.setTabOrder(self.spbThetaCol, self.spbPsiCol)
        dataTransWidget.setTabOrder(self.spbPsiCol, self.spbPhiCol)
        dataTransWidget.setTabOrder(self.spbPhiCol, self.rbAngleAero)
        dataTransWidget.setTabOrder(self.rbAngleAero, self.spbAlphaCol)
        dataTransWidget.setTabOrder(self.spbAlphaCol, self.spbBetaCol)
        dataTransWidget.setTabOrder(self.spbBetaCol, self.spbFMStartCol)
        dataTransWidget.setTabOrder(self.spbFMStartCol, self.spbFMEndCol)
        dataTransWidget.setTabOrder(self.spbFMEndCol, self.pbtnBalanceInfo)
        dataTransWidget.setTabOrder(self.pbtnBalanceInfo, self.pbtnGenerateFile)
        dataTransWidget.setTabOrder(self.pbtnGenerateFile, self.pbtnHelp)
        dataTransWidget.setTabOrder(self.pbtnHelp, self.pbtnExit)
        dataTransWidget.setTabOrder(self.pbtnExit, self.chbBatchStaticFile)
        dataTransWidget.setTabOrder(self.chbBatchStaticFile, self.pbtnBatchStaticFile)
        dataTransWidget.setTabOrder(self.pbtnBatchStaticFile, self.txtBatchStaticFile)
        dataTransWidget.setTabOrder(self.txtBatchStaticFile, self.txtBatchStaFileReg)
        dataTransWidget.setTabOrder(self.txtBatchStaFileReg, self.txtBatchDynFileReg)
        dataTransWidget.setTabOrder(self.txtBatchDynFileReg, self.pbtnBatchAddDir)
        dataTransWidget.setTabOrder(self.pbtnBatchAddDir, self.listWidgetBatchDirs)
        dataTransWidget.setTabOrder(self.listWidgetBatchDirs, self.pbtnBatchDelDir)
        dataTransWidget.setTabOrder(self.pbtnBatchDelDir, self.pbtnBatchResultDir)
        dataTransWidget.setTabOrder(self.pbtnBatchResultDir, self.txtBatchResultDir)
        dataTransWidget.setTabOrder(self.txtBatchResultDir, self.listWidgetBatchFiles)

    def retranslateUi(self, dataTransWidget):
        dataTransWidget.setWindowTitle(_translate("dataTransWidget", "天平数据转换", None))
        self.label_11.setText(_translate("dataTransWidget", "天平类型", None))
        self.cbBalanceSty.setToolTip(_translate("dataTransWidget", "选择天平类型", None))
        self.cbBalanceSty.setItemText(0, _translate("dataTransWidget", "14杆天平", None))
        self.cbBalanceSty.setItemText(1, _translate("dataTransWidget", "16杆天平", None))
        self.cbBalanceSty.setItemText(2, _translate("dataTransWidget", "18杆天平", None))
        self.cbBalanceSty.setItemText(3, _translate("dataTransWidget", "盒式天平(内)", None))
        self.cbBalanceSty.setItemText(4, _translate("dataTransWidget", "盒式天平(外)", None))
        self.pbtnBalanceParamsSetting.setText(_translate("dataTransWidget", "天平参数设置", None))
        self.groupBox.setTitle(_translate("dataTransWidget", "模型参数", None))
        self.txtDeltaY.setText(_translate("dataTransWidget", "0.", None))
        self.label_2.setText(_translate("dataTransWidget", "展长（m）", None))
        self.txtDeltaX.setText(_translate("dataTransWidget", "0.", None))
        self.txtDeltaZ.setText(_translate("dataTransWidget", "0.", None))
        self.label_6.setText(_translate("dataTransWidget", "模型重心距天平位置：", None))
        self.txtModelArea.setText(_translate("dataTransWidget", "0.", None))
        self.label.setText(_translate("dataTransWidget", "参考面积（㎡）", None))
        self.txtModelRefChord.setText(_translate("dataTransWidget", "0.", None))
        self.txtModelSpan.setText(_translate("dataTransWidget", "0.", None))
        self.txtWindSpeed.setText(_translate("dataTransWidget", "0.", None))
        self.pbtnModelDataExport.setText(_translate("dataTransWidget", "模型参数导出...", None))
        self.label_8.setText(_translate("dataTransWidget", "ΔY（m）", None))
        self.label_10.setText(_translate("dataTransWidget", "根弦长（m）", None))
        self.pbtnModelDataInput.setText(_translate("dataTransWidget", "载入模型参数", None))
        self.label_7.setText(_translate("dataTransWidget", "ΔX（m）", None))
        self.txtModelRootChord.setText(_translate("dataTransWidget", "0.", None))
        self.label_3.setText(_translate("dataTransWidget", "平均气动弦长（m）", None))
        self.label_4.setText(_translate("dataTransWidget", "实验风速（m/s）", None))
        self.label_9.setText(_translate("dataTransWidget", "ΔZ（m）", None))
        self.groupBox_2.setTitle(_translate("dataTransWidget", "数据文件", None))
        self.txtStaticFile.setPlaceholderText(_translate("dataTransWidget", "请选择静态文件", None))
        self.label_13.setText(_translate("dataTransWidget", "体轴文件", None))
        self.label_15.setText(_translate("dataTransWidget", "风轴文件", None))
        self.label_12.setText(_translate("dataTransWidget", "静态文件", None))
        self.label_14.setText(_translate("dataTransWidget", "动态文件", None))
        self.label_16.setText(_translate("dataTransWidget", "吹风数据文件目录：", None))
        self.txtBodyFile.setPlaceholderText(_translate("dataTransWidget", "请选择体轴文件", None))
        self.pbtnBodyFile.setText(_translate("dataTransWidget", "...", None))
        self.pbtnDynamicFile.setText(_translate("dataTransWidget", "...", None))
        self.txtAeroFile.setPlaceholderText(_translate("dataTransWidget", "请选择风轴文件", None))
        self.pbtnStaticFile.setText(_translate("dataTransWidget", "...", None))
        self.txtDynamicFile.setPlaceholderText(_translate("dataTransWidget", "请选择动态文件", None))
        self.pbtnAeroFile.setText(_translate("dataTransWidget", "...", None))
        self.label_17.setText(_translate("dataTransWidget", "生成数据文件目录：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSingleFile), _translate("dataTransWidget", "单文件", None))
        self.chbBatchStaticFile.setText(_translate("dataTransWidget", "单一静态文件", None))
        self.pbtnBatchStaticFile.setText(_translate("dataTransWidget", "选择静态文件", None))
        self.label_19.setText(_translate("dataTransWidget", "动/静文件校验符", None))
        self.label_18.setText(_translate("dataTransWidget", "静态文件", None))
        self.txtBatchStaFileReg.setText(_translate("dataTransWidget", "J.txt", None))
        self.label_28.setText(_translate("dataTransWidget", "动态文件", None))
        self.txtBatchDynFileReg.setText(_translate("dataTransWidget", "D.txt", None))
        self.pbtnBatchAddDir.setText(_translate("dataTransWidget", "添加目录", None))
        self.pbtnBatchDelDir.setText(_translate("dataTransWidget", "删除目录", None))
        self.pbtnBatchResultDir.setText(_translate("dataTransWidget", "生成文件存储目录", None))
        self.groupBox_10.setTitle(_translate("dataTransWidget", "待处理文件", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBatchFile), _translate("dataTransWidget", "多文件", None))
        self.groupBox_3.setTitle(_translate("dataTransWidget", "文件信息", None))
        self.label_24.setText(_translate("dataTransWidget", "Headers", None))
        self.label_25.setText(_translate("dataTransWidget", "Footers", None))
        self.chbTime.setText(_translate("dataTransWidget", "时间列", None))
        self.groupBox_9.setTitle(_translate("dataTransWidget", "角度类型与对应列", None))
        self.rbAngleEuler.setText(_translate("dataTransWidget", "欧拉角", None))
        self.chbTheta.setText(_translate("dataTransWidget", "θ", None))
        self.spbThetaCol.setToolTip(_translate("dataTransWidget", "俯仰角/支撑角", None))
        self.spbThetaCol.setStatusTip(_translate("dataTransWidget", "俯仰角/支撑角", None))
        self.spbThetaCol.setWhatsThis(_translate("dataTransWidget", "俯仰角/支撑角", None))
        self.chbPsi.setText(_translate("dataTransWidget", "ψ", None))
        self.spbPsiCol.setToolTip(_translate("dataTransWidget", "偏航角", None))
        self.spbPsiCol.setStatusTip(_translate("dataTransWidget", "偏航角", None))
        self.spbPsiCol.setWhatsThis(_translate("dataTransWidget", "偏航角", None))
        self.chbPhi.setText(_translate("dataTransWidget", "φ", None))
        self.spbPhiCol.setToolTip(_translate("dataTransWidget", "滚转角", None))
        self.spbPhiCol.setStatusTip(_translate("dataTransWidget", "滚转角", None))
        self.spbPhiCol.setWhatsThis(_translate("dataTransWidget", "滚转角", None))
        self.rbAngleAero.setText(_translate("dataTransWidget", "气动角", None))
        self.chbAlpha.setText(_translate("dataTransWidget", "α", None))
        self.spbAlphaCol.setToolTip(_translate("dataTransWidget", "迎角", None))
        self.spbAlphaCol.setStatusTip(_translate("dataTransWidget", "迎角", None))
        self.spbAlphaCol.setWhatsThis(_translate("dataTransWidget", "迎角", None))
        self.chbBeta.setText(_translate("dataTransWidget", "β", None))
        self.spbBetaCol.setToolTip(_translate("dataTransWidget", "侧滑角", None))
        self.spbBetaCol.setStatusTip(_translate("dataTransWidget", "侧滑角", None))
        self.spbBetaCol.setWhatsThis(_translate("dataTransWidget", "侧滑角", None))
        self.groupBox_5.setTitle(_translate("dataTransWidget", "力与力矩对应列", None))
        self.label_26.setToolTip(_translate("dataTransWidget", "默认力与力矩总列数为6", None))
        self.label_26.setText(_translate("dataTransWidget", "起始列", None))
        self.spbFMStartCol.setToolTip(_translate("dataTransWidget", "默认力与力矩总列数为6", None))
        self.label_27.setToolTip(_translate("dataTransWidget", "力与力矩起始列", None))
        self.label_27.setText(_translate("dataTransWidget", "终止列", None))
        self.spbFMEndCol.setToolTip(_translate("dataTransWidget", "力与力矩终止列", None))
        self.pbtnBalanceInfo.setText(_translate("dataTransWidget", "查看Info", None))
        self.pbtnGenerateFile.setText(_translate("dataTransWidget", "生成数据文件...", None))
        self.pbtnHelp.setText(_translate("dataTransWidget", "帮助", None))
        self.pbtnExit.setText(_translate("dataTransWidget", "退出", None))

import imgs_rc
