# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataDynRigTransUi.ui'
#
# Created: Sun Dec 28 14:44:25 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dataTransWidget(object):
    def setupUi(self, dataTransWidget):
        dataTransWidget.setObjectName(_fromUtf8("dataTransWidget"))
        dataTransWidget.resize(648, 782)
        dataTransWidget.setWindowTitle(_fromUtf8(""))
        self.verticalLayout_2 = QtGui.QVBoxLayout(dataTransWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.userWidget = QtGui.QWidget(dataTransWidget)
        self.userWidget.setMinimumSize(QtCore.QSize(591, 646))
        self.userWidget.setObjectName(_fromUtf8("userWidget"))
        self.verticalLayout_2.addWidget(self.userWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_4 = QtGui.QGroupBox(dataTransWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cbKineticsSty = QtGui.QComboBox(self.groupBox_4)
        self.cbKineticsSty.setObjectName(_fromUtf8("cbKineticsSty"))
        self.cbKineticsSty.addItem(_fromUtf8(""))
        self.cbKineticsSty.addItem(_fromUtf8(""))
        self.cbKineticsSty.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbKineticsSty, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.groupBox_4)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_3.addWidget(self.line_4, 0, 2, 3, 1)
        self.spbIgnorePts = QtGui.QSpinBox(self.groupBox_4)
        self.spbIgnorePts.setMaximum(10000)
        self.spbIgnorePts.setProperty("value", 200)
        self.spbIgnorePts.setObjectName(_fromUtf8("spbIgnorePts"))
        self.gridLayout_3.addWidget(self.spbIgnorePts, 1, 6, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 1, 5, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_24 = QtGui.QLabel(self.groupBox_4)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spbKineticsFre = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.spbKineticsFre.setMaximum(9999.99)
        self.spbKineticsFre.setProperty("value", 1.0)
        self.spbKineticsFre.setObjectName(_fromUtf8("spbKineticsFre"))
        self.gridLayout_5.addWidget(self.spbKineticsFre, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 2, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spbSampleRatio = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.spbSampleRatio.setMaximum(9999.99)
        self.spbSampleRatio.setProperty("value", 1000.0)
        self.spbSampleRatio.setObjectName(_fromUtf8("spbSampleRatio"))
        self.gridLayout_4.addWidget(self.spbSampleRatio, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 2, 0, 1, 1)
        self.lblPsi0 = QtGui.QLabel(self.groupBox_4)
        self.lblPsi0.setObjectName(_fromUtf8("lblPsi0"))
        self.gridLayout_3.addWidget(self.lblPsi0, 2, 3, 1, 1)
        self.spbPsi0 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.spbPsi0.setMinimum(-9999.0)
        self.spbPsi0.setMaximum(9999.99)
        self.spbPsi0.setObjectName(_fromUtf8("spbPsi0"))
        self.gridLayout_3.addWidget(self.spbPsi0, 2, 4, 1, 1)
        self.spbAmplitude = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.spbAmplitude.setMaximum(9999.99)
        self.spbAmplitude.setObjectName(_fromUtf8("spbAmplitude"))
        self.gridLayout_3.addWidget(self.spbAmplitude, 0, 6, 1, 1)
        self.spbPhi0 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.spbPhi0.setMinimum(-9999.0)
        self.spbPhi0.setMaximum(9999.99)
        self.spbPhi0.setObjectName(_fromUtf8("spbPhi0"))
        self.gridLayout_3.addWidget(self.spbPhi0, 1, 4, 1, 1)
        self.lblPhi0_2 = QtGui.QLabel(self.groupBox_4)
        self.lblPhi0_2.setObjectName(_fromUtf8("lblPhi0_2"))
        self.gridLayout_3.addWidget(self.lblPhi0_2, 0, 3, 1, 1)
        self.spbTheta0 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.spbTheta0.setMinimum(-9999.0)
        self.spbTheta0.setMaximum(9999.99)
        self.spbTheta0.setObjectName(_fromUtf8("spbTheta0"))
        self.gridLayout_3.addWidget(self.spbTheta0, 0, 4, 1, 1)
        self.lblPhi0 = QtGui.QLabel(self.groupBox_4)
        self.lblPhi0.setObjectName(_fromUtf8("lblPhi0"))
        self.gridLayout_3.addWidget(self.lblPhi0, 1, 3, 1, 1)
        self.lblAmplitude = QtGui.QLabel(self.groupBox_4)
        self.lblAmplitude.setObjectName(_fromUtf8("lblAmplitude"))
        self.gridLayout_3.addWidget(self.lblAmplitude, 0, 5, 1, 1)
        self.labCorr = QtGui.QLabel(self.groupBox_4)
        self.labCorr.setObjectName(_fromUtf8("labCorr"))
        self.gridLayout_3.addWidget(self.labCorr, 2, 5, 1, 1)
        self.spbCorr = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.spbCorr.setMinimum(0.5)
        self.spbCorr.setMaximum(1.0)
        self.spbCorr.setSingleStep(0.01)
        self.spbCorr.setProperty("value", 0.99)
        self.spbCorr.setObjectName(_fromUtf8("spbCorr"))
        self.gridLayout_3.addWidget(self.spbCorr, 2, 6, 1, 1)
        self.chbPeriodAverage = QtGui.QCheckBox(self.groupBox_4)
        self.chbPeriodAverage.setObjectName(_fromUtf8("chbPeriodAverage"))
        self.gridLayout_3.addWidget(self.chbPeriodAverage, 3, 5, 1, 2)
        self.lblPeriodNums = QtGui.QLabel(self.groupBox_4)
        self.lblPeriodNums.setObjectName(_fromUtf8("lblPeriodNums"))
        self.gridLayout_3.addWidget(self.lblPeriodNums, 3, 3, 1, 1)
        self.spbPeriodNums = QtGui.QSpinBox(self.groupBox_4)
        self.spbPeriodNums.setMinimum(1)
        self.spbPeriodNums.setMaximum(9)
        self.spbPeriodNums.setProperty("value", 8)
        self.spbPeriodNums.setObjectName(_fromUtf8("spbPeriodNums"))
        self.gridLayout_3.addWidget(self.spbPeriodNums, 3, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(dataTransWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chbButterFilter = QtGui.QCheckBox(self.groupBox)
        self.chbButterFilter.setChecked(True)
        self.chbButterFilter.setObjectName(_fromUtf8("chbButterFilter"))
        self.verticalLayout.addWidget(self.chbButterFilter)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.spbFilterOrder = QtGui.QSpinBox(self.groupBox)
        self.spbFilterOrder.setMinimum(3)
        self.spbFilterOrder.setProperty("value", 5)
        self.spbFilterOrder.setObjectName(_fromUtf8("spbFilterOrder"))
        self.gridLayout_2.addWidget(self.spbFilterOrder, 1, 1, 1, 1)
        self.spbCutoffFre = QtGui.QDoubleSpinBox(self.groupBox)
        self.spbCutoffFre.setProperty("value", 4.0)
        self.spbCutoffFre.setObjectName(_fromUtf8("spbCutoffFre"))
        self.gridLayout_2.addWidget(self.spbCutoffFre, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(dataTransWidget)
        QtCore.QObject.connect(self.chbButterFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spbCutoffFre.setEnabled)
        QtCore.QObject.connect(self.chbButterFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spbFilterOrder.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(dataTransWidget)

    def retranslateUi(self, dataTransWidget):
        self.groupBox_4.setTitle(_translate("dataTransWidget", "运动参数", None))
        self.cbKineticsSty.setItemText(0, _translate("dataTransWidget", "单独俯仰运动", None))
        self.cbKineticsSty.setItemText(1, _translate("dataTransWidget", "单独滚转运动", None))
        self.cbKineticsSty.setItemText(2, _translate("dataTransWidget", "单独偏航运动", None))
        self.label_22.setText(_translate("dataTransWidget", "运动类型", None))
        self.label_18.setText(_translate("dataTransWidget", "采样频率", None))
        self.label_21.setText(_translate("dataTransWidget", "忽略点数", None))
        self.label_24.setText(_translate("dataTransWidget", "Hz", None))
        self.label_23.setText(_translate("dataTransWidget", "Hz", None))
        self.label_19.setText(_translate("dataTransWidget", "运动频率", None))
        self.lblPsi0.setText(_translate("dataTransWidget", "偏航平衡角", None))
        self.lblPhi0_2.setText(_translate("dataTransWidget", "俯仰平衡角", None))
        self.lblPhi0.setText(_translate("dataTransWidget", "滚转平衡角", None))
        self.lblAmplitude.setText(_translate("dataTransWidget", "振幅", None))
        self.labCorr.setText(_translate("dataTransWidget", "精确度", None))
        self.chbPeriodAverage.setText(_translate("dataTransWidget", "是否周期平均", None))
        self.lblPeriodNums.setText(_translate("dataTransWidget", "使用周期数", None))
        self.groupBox.setTitle(_translate("dataTransWidget", "滤波参数设置", None))
        self.chbButterFilter.setText(_translate("dataTransWidget", "是否使用Butterworth滤波", None))
        self.label.setText(_translate("dataTransWidget", "截止频率", None))
        self.label_2.setText(_translate("dataTransWidget", "滤波阶数", None))
        self.label_4.setText(_translate("dataTransWidget", "Hz", None))

