# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataFilterUi.ui'
#
# Created: Thu Jun 26 11:07:49 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dataFilter(object):
    def setupUi(self, dataFilter):
        dataFilter.setObjectName(_fromUtf8("dataFilter"))
        dataFilter.resize(622, 541)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dataFilter.sizePolicy().hasHeightForWidth())
        dataFilter.setSizePolicy(sizePolicy)
        self.mainLayout = QtGui.QVBoxLayout(dataFilter)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.groupBox_2 = QtGui.QGroupBox(dataFilter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnRawFile = QtGui.QToolButton(self.groupBox_2)
        self.btnRawFile.setObjectName(_fromUtf8("btnRawFile"))
        self.gridLayout_2.addWidget(self.btnRawFile, 1, 5, 1, 1)
        self.btnFilterFile = QtGui.QToolButton(self.groupBox_2)
        self.btnFilterFile.setObjectName(_fromUtf8("btnFilterFile"))
        self.gridLayout_2.addWidget(self.btnFilterFile, 4, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 2, 1, 1)
        self.spbFileHeaderNums = QtGui.QSpinBox(self.groupBox_2)
        self.spbFileHeaderNums.setMaximum(10)
        self.spbFileHeaderNums.setProperty("value", 1)
        self.spbFileHeaderNums.setObjectName(_fromUtf8("spbFileHeaderNums"))
        self.gridLayout_2.addWidget(self.spbFileHeaderNums, 5, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 4, 1, 1)
        self.txtRawFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtRawFile.setObjectName(_fromUtf8("txtRawFile"))
        self.gridLayout_2.addWidget(self.txtRawFile, 1, 3, 1, 2)
        self.txtFilterFile = QtGui.QLineEdit(self.groupBox_2)
        self.txtFilterFile.setObjectName(_fromUtf8("txtFilterFile"))
        self.gridLayout_2.addWidget(self.txtFilterFile, 4, 3, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.mainLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(dataFilter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.txtSamplingRate = QtGui.QLineEdit(self.groupBox)
        self.txtSamplingRate.setObjectName(_fromUtf8("txtSamplingRate"))
        self.gridLayout_3.addWidget(self.txtSamplingRate, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 7, 1, 1)
        self.spbFilterOrders = QtGui.QSpinBox(self.groupBox)
        self.spbFilterOrders.setMinimum(1)
        self.spbFilterOrders.setMaximum(10)
        self.spbFilterOrders.setProperty("value", 5)
        self.spbFilterOrders.setObjectName(_fromUtf8("spbFilterOrders"))
        self.gridLayout_3.addWidget(self.spbFilterOrders, 0, 4, 1, 1)
        self.txtCutoffFre = QtGui.QLineEdit(self.groupBox)
        self.txtCutoffFre.setObjectName(_fromUtf8("txtCutoffFre"))
        self.gridLayout_3.addWidget(self.txtCutoffFre, 0, 6, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 8, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.mainLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chbFilterShow = QtGui.QCheckBox(dataFilter)
        self.chbFilterShow.setChecked(True)
        self.chbFilterShow.setObjectName(_fromUtf8("chbFilterShow"))
        self.horizontalLayout.addWidget(self.chbFilterShow)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnFilterStart = QtGui.QPushButton(dataFilter)
        self.btnFilterStart.setObjectName(_fromUtf8("btnFilterStart"))
        self.horizontalLayout.addWidget(self.btnFilterStart)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.mplTabWidget = QtGui.QTabWidget(dataFilter)
        self.mplTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.mplTabWidget.setObjectName(_fromUtf8("mplTabWidget"))
        self.tabCx = QtGui.QWidget()
        self.tabCx.setObjectName(_fromUtf8("tabCx"))
        self.mplTabWidget.addTab(self.tabCx, _fromUtf8(""))
        self.tabCy = QtGui.QWidget()
        self.tabCy.setObjectName(_fromUtf8("tabCy"))
        self.mplTabWidget.addTab(self.tabCy, _fromUtf8(""))
        self.tabCz = QtGui.QWidget()
        self.tabCz.setObjectName(_fromUtf8("tabCz"))
        self.mplTabWidget.addTab(self.tabCz, _fromUtf8(""))
        self.tabCmx = QtGui.QWidget()
        self.tabCmx.setObjectName(_fromUtf8("tabCmx"))
        self.mplTabWidget.addTab(self.tabCmx, _fromUtf8(""))
        self.tabCmy = QtGui.QWidget()
        self.tabCmy.setObjectName(_fromUtf8("tabCmy"))
        self.mplTabWidget.addTab(self.tabCmy, _fromUtf8(""))
        self.tabCmz = QtGui.QWidget()
        self.tabCmz.setObjectName(_fromUtf8("tabCmz"))
        self.mplTabWidget.addTab(self.tabCmz, _fromUtf8(""))
        self.mainLayout.addWidget(self.mplTabWidget)

        self.retranslateUi(dataFilter)
        self.mplTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dataFilter)
        dataFilter.setTabOrder(self.txtSamplingRate, self.btnFilterStart)

    def retranslateUi(self, dataFilter):
        dataFilter.setWindowTitle(_translate("dataFilter", "数字滤波器", None))
        self.groupBox_2.setTitle(_translate("dataFilter", "文件设置", None))
        self.btnRawFile.setText(_translate("dataFilter", "...", None))
        self.btnFilterFile.setText(_translate("dataFilter", "...", None))
        self.label_6.setText(_translate("dataFilter", "文件默认标题行数", None))
        self.spbFileHeaderNums.setSuffix(_translate("dataFilter", "行", None))
        self.label_5.setText(_translate("dataFilter", "滤波后存储文件", None))
        self.label_4.setText(_translate("dataFilter", "滤波文件", None))
        self.groupBox.setTitle(_translate("dataFilter", "滤波参数设置", None))
        self.label_7.setText(_translate("dataFilter", "Hz", None))
        self.txtSamplingRate.setText(_translate("dataFilter", "1000", None))
        self.label_8.setText(_translate("dataFilter", "Hz", None))
        self.txtCutoffFre.setText(_translate("dataFilter", "4", None))
        self.label_3.setText(_translate("dataFilter", "滤波阶数", None))
        self.label_2.setText(_translate("dataFilter", "截止频率", None))
        self.label.setText(_translate("dataFilter", "采样频率", None))
        self.chbFilterShow.setText(_translate("dataFilter", "显示波形", None))
        self.btnFilterStart.setText(_translate("dataFilter", "开始滤波", None))
        self.mplTabWidget.setTabText(self.mplTabWidget.indexOf(self.tabCx), _translate("dataFilter", "Cx", None))
        self.mplTabWidget.setTabText(self.mplTabWidget.indexOf(self.tabCy), _translate("dataFilter", "Cy", None))
        self.mplTabWidget.setTabText(self.mplTabWidget.indexOf(self.tabCz), _translate("dataFilter", "Cz", None))
        self.mplTabWidget.setTabText(self.mplTabWidget.indexOf(self.tabCmx), _translate("dataFilter", "Cmx", None))
        self.mplTabWidget.setTabText(self.mplTabWidget.indexOf(self.tabCmy), _translate("dataFilter", "Cmy", None))
        self.mplTabWidget.setTabText(self.mplTabWidget.indexOf(self.tabCmz), _translate("dataFilter", "Cmz", None))

