# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataFilterBatchUi.ui'
#
# Created: Tue Jun 24 21:30:32 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dataFilterBatch(object):
    def setupUi(self, dataFilterBatch):
        dataFilterBatch.setObjectName(_fromUtf8("dataFilterBatch"))
        dataFilterBatch.resize(671, 533)
        self.horizontalLayout = QtGui.QHBoxLayout(dataFilterBatch)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_4 = QtGui.QGroupBox(dataFilterBatch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.spbBatchFilterOrders = QtGui.QSpinBox(self.groupBox_4)
        self.spbBatchFilterOrders.setMinimum(1)
        self.spbBatchFilterOrders.setMaximum(10)
        self.spbBatchFilterOrders.setProperty("value", 5)
        self.spbBatchFilterOrders.setObjectName(_fromUtf8("spbBatchFilterOrders"))
        self.gridLayout.addWidget(self.spbBatchFilterOrders, 5, 0, 1, 1)
        self.txtBatchSampleRate = QtGui.QLineEdit(self.groupBox_4)
        self.txtBatchSampleRate.setObjectName(_fromUtf8("txtBatchSampleRate"))
        self.gridLayout.addWidget(self.txtBatchSampleRate, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.btnBatchFilterAbout = QtGui.QPushButton(self.groupBox_4)
        self.btnBatchFilterAbout.setObjectName(_fromUtf8("btnBatchFilterAbout"))
        self.gridLayout.addWidget(self.btnBatchFilterAbout, 8, 0, 1, 1)
        self.txtBatchCutoffFre = QtGui.QLineEdit(self.groupBox_4)
        self.txtBatchCutoffFre.setObjectName(_fromUtf8("txtBatchCutoffFre"))
        self.gridLayout.addWidget(self.txtBatchCutoffFre, 3, 0, 1, 1)
        self.btnBatchFilterStart = QtGui.QPushButton(self.groupBox_4)
        self.btnBatchFilterStart.setObjectName(_fromUtf8("btnBatchFilterStart"))
        self.gridLayout.addWidget(self.btnBatchFilterStart, 7, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(dataFilterBatch)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnBatchFilterFilesAdd = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBatchFilterFilesAdd.sizePolicy().hasHeightForWidth())
        self.btnBatchFilterFilesAdd.setSizePolicy(sizePolicy)
        self.btnBatchFilterFilesAdd.setObjectName(_fromUtf8("btnBatchFilterFilesAdd"))
        self.horizontalLayout_2.addWidget(self.btnBatchFilterFilesAdd)
        self.btnBatchFilterFilesClear = QtGui.QPushButton(self.groupBox)
        self.btnBatchFilterFilesClear.setObjectName(_fromUtf8("btnBatchFilterFilesClear"))
        self.horizontalLayout_2.addWidget(self.btnBatchFilterFilesClear)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.spbFilterHeaderNums = QtGui.QSpinBox(self.groupBox)
        self.spbFilterHeaderNums.setMaximum(10)
        self.spbFilterHeaderNums.setProperty("value", 1)
        self.spbFilterHeaderNums.setObjectName(_fromUtf8("spbFilterHeaderNums"))
        self.horizontalLayout_2.addWidget(self.spbFilterHeaderNums)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.txtRawFiles = QtGui.QListWidget(self.groupBox)
        self.txtRawFiles.setObjectName(_fromUtf8("txtRawFiles"))
        self.verticalLayout_2.addWidget(self.txtRawFiles)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnFilterFilesDirectory = QtGui.QPushButton(self.groupBox_3)
        self.btnFilterFilesDirectory.setObjectName(_fromUtf8("btnFilterFilesDirectory"))
        self.horizontalLayout_3.addWidget(self.btnFilterFilesDirectory)
        self.txtFilterFilesDirectory = QtGui.QLineEdit(self.groupBox_3)
        self.txtFilterFilesDirectory.setReadOnly(True)
        self.txtFilterFilesDirectory.setObjectName(_fromUtf8("txtFilterFilesDirectory"))
        self.horizontalLayout_3.addWidget(self.txtFilterFilesDirectory)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.txtFilterFiles = QtGui.QListWidget(self.groupBox_3)
        self.txtFilterFiles.setObjectName(_fromUtf8("txtFilterFiles"))
        self.verticalLayout_3.addWidget(self.txtFilterFiles)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(dataFilterBatch)
        QtCore.QMetaObject.connectSlotsByName(dataFilterBatch)

    def retranslateUi(self, dataFilterBatch):
        dataFilterBatch.setWindowTitle(_translate("dataFilterBatch", "数字滤波器批处理工具", None))
        self.groupBox_4.setTitle(_translate("dataFilterBatch", "滤波参数设置", None))
        self.label_2.setText(_translate("dataFilterBatch", "滤波阶数：", None))
        self.txtBatchSampleRate.setText(_translate("dataFilterBatch", "1000", None))
        self.label_3.setText(_translate("dataFilterBatch", "截止频率：", None))
        self.btnBatchFilterAbout.setText(_translate("dataFilterBatch", "关于...", None))
        self.txtBatchCutoffFre.setText(_translate("dataFilterBatch", "4", None))
        self.btnBatchFilterStart.setText(_translate("dataFilterBatch", "开始滤波", None))
        self.label.setText(_translate("dataFilterBatch", "采样频率（Hz）：", None))
        self.groupBox_2.setTitle(_translate("dataFilterBatch", "文件设置", None))
        self.groupBox.setTitle(_translate("dataFilterBatch", "滤波文件列表", None))
        self.btnBatchFilterFilesAdd.setText(_translate("dataFilterBatch", "添加滤波文件列表", None))
        self.btnBatchFilterFilesClear.setText(_translate("dataFilterBatch", "清空", None))
        self.label_4.setText(_translate("dataFilterBatch", "默认文件标题行数", None))
        self.groupBox_3.setTitle(_translate("dataFilterBatch", "生成滤波文件列表", None))
        self.btnFilterFilesDirectory.setText(_translate("dataFilterBatch", "添加滤波后文件目录", None))

